/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * IIR.c
 *
 * Code generation for function 'IIR'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "IIR.h"
#include "Nondirect.h"
#include "IIR_data.h"

/* Function Definitions */
double IIR(double x)
{
  /* IIR Filters input x and returns output y. */
  /*  MATLAB Code */
  /*  Generated by MATLAB(R) 8.6 and the DSP System Toolbox 9.1. */
  /*  Generated on: 07-Apr-2017 15:41:37 */
  /*  To generate C/C++ code from this function use the codegen command. */
  /*  Type 'help codegen' for more information. */
  return Nondirect_stepImpl(&Hd, x);
}

/* End of code generation (IIR.c) */
